apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-monitoring

resources:
- ../base

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
- files:
  - grafana.ini
  name: grafana-config

generatorOptions:
  disableNameSuffixHash: false
